import {
  AlertCircle,
  AlertTriangle,
  AtSign,
  Award,
  Battery,
  BatteryCharging,
  Bell,
  BellOff,
  Bluetooth,
  Bookmark,
  Box,
  Calendar,
  Camera,
  Check,
  CheckCircle,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Clock,
  Cloud,
  CloudDrizzle,
  CloudLightning,
  CloudOff,
  CloudRain,
  CloudSnow,
  Compass,
  Copy,
  Cpu,
  CreditCard,
  Database,
  DollarSign,
  Droplet,
  Edit,
  ExternalLink,
  FastForward,
  File,
  FileText,
  Filter,
  Flag,
  Folder,
  Gift,
  Grid,
  HardDrive,
  Hash,
  Headphones,
  Heart,
  HelpCircle,
  Home,
  Image,
  Inbox,
  Info,
  Layout,
  Link,
  List,
  Lock,
  LogOut,
  Mail,
  MapPin,
  Menu,
  MessageCircle,
  MessageSquare,
  Mic,
  Minus,
  Monitor,
  Moon,
  MoreHorizontal,
  MoreVertical,
  Music,
  Navigation,
  Package,
  Pause,
  Play,
  Plus,
  Repeat,
  Rewind,
  Search,
  Send,
  Server,
  Share2 as Share,
  Shield,
  ShieldOff,
  ShoppingBag,
  ShoppingCart,
  Shuffle,
  Sidebar,
  SkipBack,
  SkipForward,
  Sliders,
  Smartphone,
  Speaker,
  Star,
  Sun,
  Tablet,
  Tag,
  Thermometer,
  ThumbsDown,
  ThumbsUp,
  Tool,
  Umbrella,
  Unlock,
  User,
  UserCheck,
  UserPlus,
  Users,
  UserX,
  Video,
  Volume,
  Volume1,
  Volume2,
  VolumeX,
  Watch,
  Wifi,
  WifiOff,
  Wind,
  X,
  XCircle,
  XOctagon,
  Zap,
  ZapOff,
} from 'react-feather';
import {
  ArrowDownCircleIcon,
  ArrowDownIcon,
  ArrowLeftIcon,
  ArrowPathIcon,
  ArrowRightIcon,
  ArrowUpIcon,
  CodeBracketIcon,
  CodeBracketSquareIcon,
  Cog8ToothIcon,
  EnvelopeIcon,
  EnvelopeOpenIcon,
  ExclamationTriangleIcon,
  EyeIcon,
  EyeSlashIcon,
  FingerPrintIcon,
  KeyIcon,
  LinkSlashIcon,
  LockClosedIcon,
  LockOpenIcon,
  PhoneIcon,
  QrCodeIcon,
  TrashIcon,
  UserIcon,
} from '@heroicons/react/24/outline';

export const icons = {
  google: ExclamationTriangleIcon,
  alert: ExclamationTriangleIcon,
  alertCircle: AlertCircle,
  alertTriangle: AlertTriangle,
  arrowDown: ArrowDownIcon,
  arrowLeft: ArrowLeftIcon,
  arrowRight: ArrowRightIcon,
  arrowUp: ArrowUpIcon,
  atSign: AtSign,
  award: Award,
  battery: Battery,
  batteryCharging: BatteryCharging,
  bell: Bell,
  bellOff: BellOff,
  bluetooth: Bluetooth,
  bookmark: Bookmark,
  box: Box,
  calendar: Calendar,
  camera: Camera,
  check: Check,
  checkCircle: CheckCircle,
  chevronDown: ChevronDown,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  chevronUp: ChevronUp,
  clock: Clock,
  cloud: Cloud,
  cloudDrizzle: CloudDrizzle,
  cloudLightning: CloudLightning,
  cloudOff: CloudOff,
  cloudRain: CloudRain,
  cloudSnow: CloudSnow,
  code: CodeBracketSquareIcon,
  compass: Compass,
  copy: Copy,
  cpu: Cpu,
  creditCard: CreditCard,
  database: Database,
  dollarSign: DollarSign,
  download: ArrowDownCircleIcon,
  droplet: Droplet,
  edit: Edit,
  email: EnvelopeIcon,
  envelope: EnvelopeIcon,
  envelopeOpen: EnvelopeOpenIcon,
  externalLink: ExternalLink,
  eye: EyeIcon,
  eyeOff: EyeSlashIcon,
  fastForward: FastForward,
  file: File,
  fileText: FileText,
  filter: Filter,
  fingerPrint: FingerPrintIcon,
  flag: Flag,
  folder: Folder,
  gift: Gift,
  grid: Grid,
  hardDrive: HardDrive,
  hardware_token: FingerPrintIcon,
  hash: Hash,
  headphones: Headphones,
  heart: Heart,
  helpCircle: HelpCircle,
  home: Home,
  image: Image,
  inbox: Inbox,
  info: Info,
  key: KeyIcon,
  layout: Layout,
  link: Link,
  list: List,
  lock: Lock,
  lockClosed: LockClosedIcon,
  lockOpen: LockOpenIcon,
  logout: LogOut,
  lookup_secret: CodeBracketIcon,
  mail: Mail,
  mapPin: MapPin,
  menu: Menu,
  message: MessageSquare,
  messageCircle: MessageCircle,
  mic: Mic,
  minus: Minus,
  monitor: Monitor,
  moon: Moon,
  moreHorizontal: MoreHorizontal,
  moreVertical: MoreVertical,
  music: Music,
  navigation: Navigation,
  offline_access: UserIcon,
  openid: UserIcon,
  package: Package,
  passkey: FingerPrintIcon,
  password: LockClosedIcon,
  pause: Pause,
  phone: PhoneIcon,
  play: Play,
  plus: Plus,
  profile: UserIcon,
  qrCode: QrCodeIcon,
  refresh: ArrowPathIcon,
  repeat: Repeat,
  rewind: Rewind,
  search: Search,
  send: Send,
  server: Server,
  settings: Cog8ToothIcon,
  share: Share,
  shield: Shield,
  shieldOff: ShieldOff,
  shoppingBag: ShoppingBag,
  shoppingCart: ShoppingCart,
  shuffle: Shuffle,
  sidebar: Sidebar,
  skipBack: SkipBack,
  skipForward: SkipForward,
  sliders: Sliders,
  smartphone: Smartphone,
  speaker: Speaker,
  star: Star,
  sun: Sun,
  tablet: Tablet,
  tag: Tag,
  thermometer: Thermometer,
  thumbsDown: ThumbsDown,
  thumbsUp: ThumbsUp,
  tool: Tool,
  totp: QrCodeIcon,
  trash: TrashIcon,
  umbrella: Umbrella,
  unlink: LinkSlashIcon,
  unlock: Unlock,
  user: User,
  userCheck: UserCheck,
  userPlus: UserPlus,
  userX: UserX,
  users: Users,
  video: Video,
  volume1: Volume1,
  volume2: Volume2,
  volume: Volume,
  volumeX: VolumeX,
  watch: Watch,
  webauthn: KeyIcon,
  wifi: Wifi,
  wifiOff: WifiOff,
  wind: Wind,
  x: X,
  xCircle: XCircle,
  xOctagon: XOctagon,
  zap: Zap,
  zapOff: ZapOff,
} as const;

export type IconName = keyof typeof icons;
